### ISSUE TITLE
gtk 3.20 issues

### ISSUE THREAD

**Issue by vdubikhin** [originalseed/darkcold#3]
The new gtk 3.20 update introduced some issues with this theme: windows background is plain dark(instead of theme image) and list windows have transparent background.

**Comment by chewi** [comment]
Some dialog windows have a transparent background too. It's a bit of a car crash at the moment.

**Comment by chewi** [comment]
I held off as long as I could but now my Gentoo system has also updated so I'll have to say goodbye to this theme altogether. :cry:

**Comment by originalseed** [comment]
@vdubikhin @chewi Thanks for your input.
I have started working on gtk 3.20 version, it will take a while to complete.

**Comment by chewi** [comment]
Great! @vdubikhin pointed me to [an alternative theme based on DarkCold](https://www.xfce-look.org/content/show.php/Plasma+Bolt,+Fire,+Shock?content=158436) that does work. Maybe you could get some pointers from that. I just need to work out which one I like best. :wink:

**Comment by kilobyte** [comment]
I've just noticed what you pushed 27 days ago (and had on your disk many months ago) -- it already works drastically better than the pretender, Plasma {Fire,Shock,Bolt} (that theme has elements changing size when unselected, black-on-black text, etc).  Care to make a release soon?

In current version, menu bar appears to be squished (appearing to be clipped) in some programs (like XFCE Terminal), but in (very brief) testing I noticed no show-stopping bugs.

**Comment by kilobyte** [comment]
Would you mind if I packaged this theme for Debian (and thus also most derivatives) as-is?  Or should I hold my horses and wait?

Things I'm currently unhappy about are:
 * ugly menu bars (a matter of taste)
 * too dark text in Firefox' drop-down URL bar and certain dialogs
 * lots of error message spam when starting a GTK3 program from a terminal

but none of the above is bad enough.

**Comment by kilobyte** [comment]
With originalseed being gone (no response on any e-mail addresses I found), I forked the theme (https://github.com/kilobyte/darkcold) with some fixes.  It'll hit Debian once FTPmasters review it.

I did not rename — when/if originalseed is back, please incorporate my fixes (possibly rejecting some), I'll switch to your branch then.

**Comment by kilobyte** [comment]
... and in Debian unstable.  This also includes Ubuntu bionic upon their next sync.

Thus, could you guys please test my fixes?  With the theme having wider distribution, it'd be nice to fix remaining problems **before** becoming non-updateable (Ubuntu LTS will go out in April).

**Comment by originalseed** [comment]
Sorry for not responding for such a long time.  Any help with bringing this theme up to current standards will be welcomed!!!

**Comment by kilobyte** [comment]
It's awesome to hear you're back!  Even though people switch or abandon e-mail addresses, or stop responding, they never do this for many ones at once, thus I guessed that something bad happened to you — great to know this assumption was unfounded.

With the fixes I sent (most of which you already merged), it seems to me that GTK 3.20/22 is fully functional, thus I propose merging the issue_3 branch into master (it's a fast forward) and marking this done.  Any extra improvements would be polishing.

**Comment by originalseed** [comment]
issue_3 merged into master and a tag is created. I have tested with latest fedora-gnome 28 and mint-cinnamon 19 and theme behaved "functional". There is more work to be done to make gtk3.20 behave more like gtk3.0 but for now its good enough.
