### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by kilobyte** [originalseed/darkcold#7]
To be able to package the theme, I needed a version number.  There were no tags and the tarball names on Gnome-Look are inconsistent, thus I went with ``1.0``.  That particular release is set in stone as at it got for example into Ubuntu 18.04 LTS.

It would be nice if you provided official tag[s].  The only requirement being that 1.0 is already taken (without your consent, but it looked like you won't be coming back).

**Comment by originalseed** [comment]
Tag created.
